name: Deploy Production

on:
  push:
    tags:
      - 'v*'
    paths:
      - 'environments/prod/**'
      - '.github/workflows/deploy-prod.yml'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.2

      - name: Terraform Init
        working-directory: environments/prod
        run: terraform init

      - name: Terraform Plan
        working-directory: environments/prod
        run: terraform plan -var-file=terraform.tfvars

      - name: Terraform Apply
        working-directory: environments/prod
        run: terraform apply -auto-approve -var-file=terraform.tfvars
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 